### PR TITLE
Adding hydrodynamics and mooring sections to OWENS Dev Guide

### LINKED ISSUE #79: Add Hydrodynamics and Mooring sections to Dev Guide
https://github.com/sandialabs/OWENS.jl/blob/master/docs/src/OWENS_Dev_Guide.md#hydrodynamics

https://github.com/sandialabs/OWENS.jl/blob/master/docs/src/OWENS_Dev_Guide.md#mooring

### PR DESCRIPTION
**Pull request by michaelcdevin**
This provides "under the hood" details on the internal solve procedure and OWENS structures for floating capabilities, in the event that future developers modify any of this. There is one TODO in this that will point to a floating capabilities literate notebook, which I will get to shortly. The notebook will include some top-level details about the syntax for the platform mesh that will be relevant to all users.

Closes #79

### CODE REVIEW

**Comment by michaelcdevin** [comment]
@kevmoor This is ready for your review (doesn't look like I can assign you as a reviewer in the PR for some reason).

**Review by kevmoor — APPROVED** [review]
The one items is the zcm not being in the anticipated direction.  Maybe we just open an issue and leave this as is.

**Comment by michaelcdevin** [comment]
Sounds good, I will create a new issue for the zcm problem and then merge this.

**Comment by michaelcdevin** [comment]
Created #83 for the one outstanding issue, merging this now. Thanks for the review!

**Pull request merged**
